language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - sudo apt-get -qq update && sudo apt-get -qq install graphviz
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then if [ ${TRAVIS_PHP_VERSION%%.*} -ge 7 ]; then echo "yes\n" | pecl install apcu; else echo "yes\n" | pecl install apcu-4.0.10; fi; echo 'extension=apcu.so' >> ./php.ini; else echo 'extension=apc.so' >> ./php.ini; fi"
  - composer install --prefer-source
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then phpenv config-add ./php.ini; fi"

script:
  - mkdir -p build/logs
  - phpunit --verbose --coverage-clover build/logs/clover.xml
  - php vendor/bin/athletic -p benchmarks

after_script:
  - php vendor/bin/coveralls
