language: php

php:
  - 7.4

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - yes '' | pecl install -f apcu
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --prefer-source

script:
  - mkdir -p build/logs
  - ./vendor/bin/psalm --no-progress
  - ./vendor/bin/php-cs-fixer fix -v --dry-run --stop-on-violation --using-cache=no
  - ./vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
  - travis_retry php ./vendor/bin/php-coveralls
