language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - sudo apt-get -qq update && sudo apt-get -qq install graphviz
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then if [ ${TRAVIS_PHP_VERSION//./} -ge 70 ]; then echo "yes\n" | pecl install apcu; else echo "yes\n" | pecl install apcu-4.0.10; fi; echo 'extension=apcu.so' >> ./php.ini; else echo 'extension=apc.so' >> ./php.ini; fi"
  - composer install --prefer-source
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then phpenv config-add ./php.ini; fi"

script:
  - mkdir -p build/logs
  - php ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - travis_retry php ./vendor/bin/coveralls
